"""AEM (Abstract Execution Machine) halt codes — host-independent runtime classification."""

from __future__ import annotations

AEM_PRECOND_FALSE = "AEM_PRECOND_FALSE"
AEM_FORBID_TRUE = "AEM_FORBID_TRUE"
AEM_POSTCOND_FALSE = "AEM_POSTCOND_FALSE"
AEM_EFFECT_REJECT = "AEM_EFFECT_REJECT"
AEM_EFFECT_EXN = "AEM_EFFECT_EXN"
AEM_EVAL_UNDEF = "AEM_EVAL_UNDEF"
AEM_EVAL_TYPE = "AEM_EVAL_TYPE"
AEM_STATE_MISMATCH = "AEM_STATE_MISMATCH"
